name: HTTP Protocol Testing CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up the Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Lint with ruff
        run: |
          ruff check
      - name: Type check with mypy
        run: |
          mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
      - name: Run unit tests
        run: |
          pytest tests/unit/ --cov=. --cov-report=xml
      - name: Run integration tests
        run: |
          pytest tests/integration/ --cov=. --cov-report=xml --cov-append
